### ISSUE TITLE
The current language button on header should be active

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#65]

**Comment by jpenanje** [comment]
on it now

**Comment by jpenanje** [comment]
I used "<li><a href="/" class="{{ request()->is('/') ? 'active' : '' }}">home</a></li>" when rendering links on the navbar active.
request()->is() makes use of the route to determine is the link was clicked on.

Trying to implement this method for this issue but it seems not to work. @Fenn-CS

**Comment by Fenn-CS** [comment]
@jpenanje You can't use that, because the current language is not tracked via a route. It's tracked in the session variable.  So you have to session to be able to implement the check.

See:

https://github.com/whilesmart/lasodec/blob/2dbe9f3f363b4a6f1a59a434a1acd8b4eb33307e/app/Http/Controllers/LocalizationController.php#L10-L20

and  https://github.com/whilesmart/lasodec/pull/20
